apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-app
  labels:
    team: bbdpoc-eks-flux-team
spec:
  selector:
    matchLabels:
      app: backend
  endpoints:
  - port: http